name: GapCooldown
main: BigDGucci\GapCooldown\Main
author: BigDGucci
version: 0.1
api:
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12
- 3.0.0-ALPHA13
- 3.0.0-ALPHA14
- 3.0.0-ALPHA15
- 3.0.0-ALPHA16
- 3.0.0-ALPHA17
- 3.0.0-ALPHA18
- 3.0.0-ALPHA19
- 3.0.0-ALPHA20
